/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	mysamplecontrollerv1 "github.com/alice02/crd-controller-sample/pkg/apis/mysamplecontroller/v1"
	versioned "github.com/alice02/crd-controller-sample/pkg/client/clientset/versioned"
	internalinterfaces "github.com/alice02/crd-controller-sample/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/alice02/crd-controller-sample/pkg/client/listers/mysamplecontroller/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SampleResourceInformer provides access to a shared informer and lister for
// SampleResources.
type SampleResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SampleResourceLister
}

type sampleResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSampleResourceInformer constructs a new informer for SampleResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSampleResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSampleResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSampleResourceInformer constructs a new informer for SampleResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSampleResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().SampleResources(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1().SampleResources(namespace).Watch(options)
			},
		},
		&mysamplecontrollerv1.SampleResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *sampleResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSampleResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sampleResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mysamplecontrollerv1.SampleResource{}, f.defaultInformer)
}

func (f *sampleResourceInformer) Lister() v1.SampleResourceLister {
	return v1.NewSampleResourceLister(f.Informer().GetIndexer())
}
