/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	mysamplecontrollerv1 "github.com/alice02/crd-controller-sample/pkg/apis/mysamplecontroller/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSampleResources implements SampleResourceInterface
type FakeSampleResources struct {
	Fake *FakeExampleV1
	ns   string
}

var sampleresourcesResource = schema.GroupVersionResource{Group: "example.com", Version: "v1", Resource: "sampleresources"}

var sampleresourcesKind = schema.GroupVersionKind{Group: "example.com", Version: "v1", Kind: "SampleResource"}

// Get takes name of the sampleResource, and returns the corresponding sampleResource object, and an error if there is any.
func (c *FakeSampleResources) Get(name string, options v1.GetOptions) (result *mysamplecontrollerv1.SampleResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sampleresourcesResource, c.ns, name), &mysamplecontrollerv1.SampleResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mysamplecontrollerv1.SampleResource), err
}

// List takes label and field selectors, and returns the list of SampleResources that match those selectors.
func (c *FakeSampleResources) List(opts v1.ListOptions) (result *mysamplecontrollerv1.SampleResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sampleresourcesResource, sampleresourcesKind, c.ns, opts), &mysamplecontrollerv1.SampleResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &mysamplecontrollerv1.SampleResourceList{ListMeta: obj.(*mysamplecontrollerv1.SampleResourceList).ListMeta}
	for _, item := range obj.(*mysamplecontrollerv1.SampleResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sampleResources.
func (c *FakeSampleResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sampleresourcesResource, c.ns, opts))

}

// Create takes the representation of a sampleResource and creates it.  Returns the server's representation of the sampleResource, and an error, if there is any.
func (c *FakeSampleResources) Create(sampleResource *mysamplecontrollerv1.SampleResource) (result *mysamplecontrollerv1.SampleResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sampleresourcesResource, c.ns, sampleResource), &mysamplecontrollerv1.SampleResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mysamplecontrollerv1.SampleResource), err
}

// Update takes the representation of a sampleResource and updates it. Returns the server's representation of the sampleResource, and an error, if there is any.
func (c *FakeSampleResources) Update(sampleResource *mysamplecontrollerv1.SampleResource) (result *mysamplecontrollerv1.SampleResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sampleresourcesResource, c.ns, sampleResource), &mysamplecontrollerv1.SampleResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mysamplecontrollerv1.SampleResource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSampleResources) UpdateStatus(sampleResource *mysamplecontrollerv1.SampleResource) (*mysamplecontrollerv1.SampleResource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sampleresourcesResource, "status", c.ns, sampleResource), &mysamplecontrollerv1.SampleResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mysamplecontrollerv1.SampleResource), err
}

// Delete takes name of the sampleResource and deletes it. Returns an error if one occurs.
func (c *FakeSampleResources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sampleresourcesResource, c.ns, name), &mysamplecontrollerv1.SampleResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSampleResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sampleresourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &mysamplecontrollerv1.SampleResourceList{})
	return err
}

// Patch applies the patch and returns the patched sampleResource.
func (c *FakeSampleResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *mysamplecontrollerv1.SampleResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sampleresourcesResource, c.ns, name, pt, data, subresources...), &mysamplecontrollerv1.SampleResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mysamplecontrollerv1.SampleResource), err
}
